# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run unit tests"
  lane :unit_test do
    gradle(task: "test")
  end

  desc "Run feature tests"
  lane :feature_test do
    gradle(task: "connectedAndroidTest")
  end

  desc "Run all tests"
  lane :test do
    unit_test
    feature_test
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: "beta")
  end
end
